name: Publish a latest image

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to OCI registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login oci-registry.kennfatt.dev -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push image
        run: |
          docker build -t kennfatt.space:latest .
          docker tag kennfatt.space:latest oci-registry.kennfatt.dev/kennfatt.space:latest
          docker push oci-registry.kennfatt.dev/kennfatt.space:latest