name: Deploy on Private Server

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull --force origin main
            yarn build
            pm2 restart ${{ secrets.APP_PM2_IDENTIFIER }}
